#!/usr/bin/env bash
# Configures Ngninx server so that /redirect_me is redirecting to another page
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
FILE=/etc/nginx/sites-available/default
REDIRECT_STRING="location /redirect_me {\n return 301 http://www.google.com;\n}\n"
    sudo sed -i '12a\'"$REDIRECT_STRING" $FILE
sudo service nginx restart
