#!/usr/bin/env bash
# Bash script to Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo service nginx start
rdt="location /redirect_me {\n return 301 http://www.google.com;\n}\n"
sudo sed -i "30i $rdt" /etc/nginx/sites-available/default
sudo service nginx restart
