#!/usr/bin/env bash
#install haproxy and configure on system
sudo apt-get update

sudo apt-get install haproxy=2.8.\*

sudo nano /etc/hostname

FILE=/etc/haproxy/haproxy.cfg
echo -e "frontend web-frontend
\tbind *:80
\tmode http
\tdefault_backend web_backend
backend web_backend
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver web-01 100.25.2.92:80 check
\tserver web-02 54.172.76.0:80 check" | sudo tee -a $FIL

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
sudo service haproxy restart
