#!/usr/bin/env bash
#install haproxy and configure on system
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

sudo hostname 404752-web-01
sudo nano /etc/hostname
sudo hostname 404752-web-02
sudo nano /etc/hostname

FILE=/etc/haproxy/haproxy.cfg
echo -e "frontend web-frontend
\tbind *:80
\tmode http
\tdefault_backend web_backend
backend web_backend
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver web-01 100.25.2.92:80 check
\tserver web-02 54.172.76.0:80 check" | sudo tee -a $FILE
# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
sudo service haproxy restart
